export const INCREMENT_APPLE = 'INCREMENT_APPLE';
export const DECREMENT_APPLE = 'DECREMENT_APPLE';
export const INCREMENT_BANANA = 'INCREMENT_BANANA';
export const DECREMENT_BANANA = 'DECREMENT_BANANA';
